#!/usr/bin/env bash
# post-merge

# Only run when pulling master (optional check)
current_branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$current_branch" = "master" ]; then
  # Run your apply script
  ./apply.sh
fi

