gui:
  border: "rounded"
  nerdFontsVersion: "3"
os:
  #  If vscode cli is installed
  # open: "code {{filename}}"
  # open: "~/Apps/Visual\\ Studio\\ Code.app/contents/Resources/app/bin/code {{filename}}"
git:
  branchPrefix: "feature/PPP-"
  commitPrefix:
    pattern: "feature\\/([A-Z]+-\\d+)"
    replace: "$0 "
