import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Windowed"
decorations = "Buttonless"
opacity = 0.98
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14.0

[[keyboard.bindings]]
chars = "\u0001" # Ctrl + A
key = "A"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0002" # Ctrl + B
key = "B"
mods = "Command"
# [[keyboard.bindings]]
# chars = "\u0003" # Ctrl + C
# key = "C"
# mods = "Command"
[[keyboard.bindings]]
chars = "\u0004" # Ctrl + D
key = "D"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0005" # Ctrl + E
key = "E"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0006" # Ctrl + F
key = "F"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0007" # Ctrl + G
key = "G"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0008" # Ctrl + H
key = "H"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0009" # Ctrl + I
key = "I"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000a" # Ctrl + J
key = "J"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000b" # Ctrl + K
key = "K"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000c" # Ctrl + L
key = "L"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000d" # Ctrl + M
key = "M"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000e" # Ctrl + N
key = "N"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000f" # Ctrl + O
key = "O"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0010" # Ctrl + P
key = "P"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0011" # Ctrl + Q
key = "Q"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0012" # Ctrl + R
key = "R"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0013" # Ctrl + S
key = "S"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0014" # Ctrl + T
key = "T"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0015" # Ctrl + U
key = "U"
mods = "Command"
# [[keyboard.bindings]]
# chars = "\u0016" # Ctrl + V
# key = "V"
# mods = "Command"
[[keyboard.bindings]]
chars = "\u0017" # Ctrl + W
key = "W"
mods = "Command"
# [[keyboard.bindings]]
# chars = "\u0018" # Ctrl + X
# key = "X"
# mods = "Command"
[[keyboard.bindings]]
chars = "\u0019" # Ctrl + Y
key = "Y"
mods = "Command"
[[keyboard.bindings]]
chars = "\u001a" # Ctrl + Z
key = "Z"
mods = "Command"
[[keyboard.bindings]] # Ctrl + /
chars = "\u001f"
key = "/"
mods = "Command"
[[keyboard.bindings]] # Ctrl + \
chars = "\u001c"
key = "\\"
mods = "Command"
[[keyboard.bindings]] # Ctrl + [
chars = "\u001b"
key = "["
mods = "Command"
[[keyboard.bindings]] # Ctrl + ]
chars = "\u001d"
key = "]"
mods = "Command"
[[keyboard.bindings]] # Ctrl + ;
chars = "\u001b"
key = ";"
mods = "Command"
[[keyboard.bindings]] # Ctrl + '
chars = "\u001b"
key = "'"
mods = "Command"
[[keyboard.bindings]] # Ctrl + `
chars = "\u001b"
key = "`"
mods = "Command"
[[keyboard.bindings]] # Ctrl + -
chars = "\u001f"
key = "-"
mods = "Command"
[[keyboard.bindings]] # Ctrl + =
chars = "\u001f"
key = "="
mods = "Command"
[[keyboard.bindings]] # Ctrl + ,
chars = "\u001f"
key = ","
mods = "Command"
[[keyboard.bindings]] # Ctrl + .
chars = "\u001f"
key = "."
mods = "Command"
[[keyboard.bindings]] # Ctrl + Enter
action = "ToggleSimpleFullscreen"
key = "Enter"
mods = "Command"
