import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Windowed"
decorations = "Buttonless"
opacity = 0.99
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13.0
builtin_box_drawing = false

[[keyboard.bindings]]
chars = "\u0001" # Ctrl + A
key = "A"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0002" # Ctrl + B
key = "B"
mods = "Command"
# [[keyboard.bindings]]
# chars = "\u0003" # Ctrl + C
# key = "C"
# mods = "Command"
[[keyboard.bindings]]
chars = "\u0004" # Ctrl + D
key = "D"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0005" # Ctrl + E
key = "E"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0006" # Ctrl + F
key = "F"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0007" # Ctrl + G
key = "G"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0008" # Ctrl + H
key = "H"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0009" # Ctrl + I
key = "I"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000a" # Ctrl + J
key = "J"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000b" # Ctrl + K
key = "K"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000c" # Ctrl + L
key = "L"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000d" # Ctrl + M
key = "M"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000e" # Ctrl + N
key = "N"
mods = "Command"
[[keyboard.bindings]]
chars = "\u000f" # Ctrl + O
key = "O"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0010" # Ctrl + P
key = "P"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0011" # Ctrl + Q
key = "Q"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0012" # Ctrl + R
key = "R"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0013" # Ctrl + S
key = "S"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0014" # Ctrl + T
key = "T"
mods = "Command"
[[keyboard.bindings]]
chars = "\u0015" # Ctrl + U
key = "U"
mods = "Command"
# [[keyboard.bindings]]
# chars = "\u0016" # Ctrl + V
# key = "V"
# mods = "Command"
[[keyboard.bindings]]
chars = "\u0017" # Ctrl + W
key = "W"
mods = "Command"
# [[keyboard.bindings]]
# chars = "\u0018" # Ctrl + X
# key = "X"
# mods = "Command"
[[keyboard.bindings]]
chars = "\u0019" # Ctrl + Y
key = "Y"
mods = "Command"
[[keyboard.bindings]]
chars = "\u001a" # Ctrl + Z
key = "Z"
mods = "Command"

# {key = "A", mods = "Control | Shift", chars = "\u002b[65;6u" },
# {key = "B", mods = "Control | Shift", chars = "\u001b[66;6u" },
# {key = "C", mods = "Control | Shift", chars = "\u001b[67;6u" },
# {key = "D", mods = "Control | Shift", chars = "\u001b[68;6u" },
# {key = "E", mods = "Control | Shift", chars = "\u001b[69;6u" },
# {key = "F", mods = "Control | Shift", chars = "\u001b[70;6u" },
# {key = "G", mods = "Control | Shift", chars = "\u001b[71;6u" },
# {key = "H", mods = "Control | Shift", chars = "\u001b[72;6u" },
# {key = "I", mods = "Control | Shift", chars = "\u001b[73;6u" },
# {key = "J", mods = "Control | Shift", chars = "\u001b[74;6u" },
# {key = "K", mods = "Control | Shift", chars = "\u001b[75;6u" },
# {key = "L", mods = "Control | Shift", chars = "\u001b[76;6u" },
# {key = "M", mods = "Control | Shift", chars = "\u001b[77;6u" },
# {key = "N", mods = "Control | Shift", chars = "\u001b[78;6u" },
# {key = "O", mods = "Control | Shift", chars = "\u001b[79;6u" },
# {key = "P", mods = "Control | Shift", chars = "\u001b[80;6u" },
# {key = "Q", mods = "Control | Shift", chars = "\u001b[81;6u" },
# {key = "R", mods = "Control | Shift", chars = "\u001b[82;6u" },
# {key = "S", mods = "Control | Shift", chars = "\u001b[83;6u" },
# {key = "T", mods = "Control | Shift", chars = "\u001b[84;6u" },
# {key = "U", mods = "Control | Shift", chars = "\u001b[85;6u" },
# {key = "V", mods = "Control | Shift", chars = "\u001b[86;6u" },
# {key = "W", mods = "Control | Shift", chars = "\u001b[87;6u" },
# {key = "X", mods = "Control | Shift", chars = "\u001b[88;6u" },
# {key = "Y", mods = "Control | Shift", chars = "\u001b[89;6u" },
# {key = "Z", mods = "Control | Shift", chars = "\u001b[90;6u"},
# {key="Key0", mods= "Control", chars= "\u001b[48;5u" },
# {key="Key1", mods= "Control", chars= "\u001b[49;5u" },
# {key="Key2", mods= "Control", chars= "\u001b[50;5u" },
# {key="Key3", mods= "Control", chars= "\u001b[51;5u" },
# {key="Key4", mods= "Control", chars= "\u001b[52;5u" },
# {key="Key5", mods= "Control", chars= "\u001b[53;5u" },
# {key="Key6", mods= "Control", chars= "\u001b[54;5u" },
# {key="Key7", mods= "Control", chars= "\u001b[55;5u" },
# {key="Key8", mods= "Control", chars= "\u001b[56;5u" },
# {key="Key9", mods= "Control", chars= "\u001b[57;5u" }

[[keyboard.bindings]]
chars = "\u001b[72;6u" # Ctrl + Shift + H
key = "H"
mods = "Command|Shift"
[[keyboard.bindings]]
chars = "\u001b[74;6u" # Ctrl + Shift + J
key = "J"
mods = "Command|Shift"
[[keyboard.bindings]]
chars = "\u001b[75;6u" # Ctrl + Shift + K
key = "K"
mods = "Command|Shift"
[[keyboard.bindings]]
chars = "\u001b[76;6u" # Ctrl + Shift + L
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]] # Ctrl + /
chars = "\u001f"
key = "/"
mods = "Command"
[[keyboard.bindings]] # Ctrl + \
chars = "\u001c"
key = "\\"
mods = "Command"
[[keyboard.bindings]] # Ctrl + Up
chars = "\u001b[A"
key = "Up"
mods = "Command"
[[keyboard.bindings]] # Ctrl + Enter
action = "ToggleSimpleFullscreen"
key = "Enter"
mods = "Command"
[[keyboard.bindings]] # Ctrl + N
action = "SpawnNewInstance"
key = "W"
mods = "Command"
